flask-alchemy/pos/models/login.py
from pos.models import db


class TB_user(db.Model):
    id_user = db.Column(db.Integer, primary_key=True, autoincrement=True)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    username = db.Column(db.String(50), nullable=False)
    password = db.Column(db.String(120), nullable=False)
    email = db.Column(db.String(50), nullable=False)

    def __init__(self, username, password, email):
        self.username = username
        self.password = password
        self.email = email
        self.registered_on = datetime.utcnow()

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    def __repr__(self):
        return '<User %r>' % (self.username)

flask-alchemy/pos/views/login.py
from flask import Blueprint, render_template, request, redirect, url_for
from pos.models import db
from pos.models.login import TB_user

bp = Blueprint("login", __name__)

# method login


@bp.route("/login")
def login():
    # Jika belum login maka di arah ke login.html
    if request.method == 'GET':
        return render_template('login.html')
    # Jika sudah login
    return redirect(url_for('product'))


def register():
    if request.method == 'GET':
        return render_template('register.html')
    user = TB_user(request.form['username'], request.form['password'],
                   request.form['email'])
    db.session.add(user)
    db.session.commit()
    # flash('User successfully registered')
    return redirect(url_for('login'))

flask-alchemy/pos/views/product.py
from flask import Blueprint, render_template, request, redirect
from pos.models import db
from pos.models.product import Product

bp = Blueprint("product", __name__)


@bp.route("/product")
def product_list():
    """List product"""

    # mengambil semua product
    product = Product.query.all()
    return render_template("product/list.html", product=product)


@bp.route("/product/add", methods=["POST", "GET"])
def product_add():
    """Add product"""
    if request.method == "GET":
        return render_template('product/form_add.html')

    # get from form
    name = request.form["name"]
    price = request.form["price"]
    stock = request.form['stock']

    # jika lupa cara menyimpan buka notebook sebelumnya
    product = Product()
    product.name = name
    product.price = price
    product.stock = stock
    db.session.add(product)
    db.session.commit()

    # setelah simpan selesai redirect ke list product
    return redirect("/product")


@bp.route("/product/update", methods=["POST", "GET"])
def product_update():
    """Update product"""
    product_id = request.args['id']

    if request.method == "GET":
        # get product by id
        product = Product.query.filter_by(id=product_id).first()

        # tampilkan data produk yang akan di update
        return render_template('product/form_edit.html', product=product)

    # ambil data form
    name = request.form['name']
    price = request.form['price']
    stock = request.form['stock']

    # get product by id
    product = Product.query.filter_by(id=product_id).first()

    # update product
    product.name = name
    product.price = price
    product.stock = stock
    db.session.add(product)
    db.session.commit()

    # redirect ke list product
    return redirect("/product")


@bp.route("/product/delete")
def product_delete():
    """Delete product"""
    product_id = request.args['id']
    product = Product.query.filter_by(id=product_id).first()
    if product:
        # delete product by id
        db.session.delete(product)
        db.session.commit()

    return redirect("/product")

flask-alchemy/pos/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FLASK-SQLALCHEMY</title>

    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">

    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
      <nav class="navbar navbar-default ">
          <div class="container-fluid">
              <ul class="nav navbar-nav">
                  <li><a href="/product">list product</a></li>
                  <li><a href="/product/add">add product</a></li>
                  <li><a href="/transaction">list transaction</a></li>
                  <li><a href="/transaction/add">add transaction</a></li>
              </ul>
          </div>
      </nav>
      <div class="container">
          {% block content %}{% endblock %}
      </div>

    <script src="/assets/js/jquery-min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>

flask-alchemy/pos/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FLASK-ALCHEMY</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
      <div class="container">
          <div class="panel panel-info">
              <div class="panel-heading">
                      <h1>FLASK SQL-ALCHEMY<small>oleh Yunindyo Prabowo</small></h1>
              </div>
          </div>
          {% block content %}
          <div class="row">
              <div class="col-md-4">
              </div>
              <div class="col-md-4">
                  <div class="panel panel-primary">
                      <div class="panel-heading">
                              <center>Flask-SqlAlchemy</center>
                      </div>
                      <div class="panel-body">
                          <header>
                              Aplikasi <i>Point Of Sales</i> menggunakan Flask dengan Modelling menggunakan
                              ORM Flask-SqlAlchemy dan <i>Blueprint</i>
                          </header>
                      </div>
                      <center>
                           <a href="{{url_for('product.product_list')}}" class="btn btn-info" role="button">Return Apps </a>
                       </center>
                  </div>
              </div>
              <div class="col-md-4">
              </div>
          </div>
          {% endblock %}
      </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/assets/js/jquery-min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>

flask-alchemy/pos/templates/login.html
{% extends "index.html" %}
{% block content %}

<div class="container-fluid">

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h4 style="border-bottom: 1px solid #c5c5c5;">
                <span class="glyphicon glyphicon-user"></span>
                Account Login
            </h4>

            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong></strong>
            </div>

            <form action="" method="POST" style="padding:20px;">
                <div class="form-group input-group">
                    <span class="input-group-addon">
                        @
                    </span>
                    <input class="form-control" placeholder="username" name="username" type="username" required="" autofocus="">
                </div>
                <div class="form-group input-group">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-lock"></i>
                    </span>
                    <input class="form-control" placeholder="Password" name="password" type="password" value="" required="">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">
                        Access
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}